version: '3'

services:
  with:
    container_name: ansible-runner
    image: ansible-runner-img
    build: .
    working_dir: /app
    environment:
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - .:/app
      - ${HOME}/.aws:/root/.aws
    tty: true