---
#Input:
#  network_vpc_name_r: {}
#  network_vpc_cidr_r: {}
#  network_vpc_region_r: {}
#  network_igw_tag_name_r: {}
#  network_subnet_az_r: {}
#  network_subnet_cidr_r: {}
#  network_subnet_name_r: {}

- include: ../../../modules/create/vpc.yml
  vars:
    vpc_name_r: "{{ network_vpc_name_r }}"
    vpc_cidr_r: "{{ network_vpc_cidr_r }}"
    vpc_region_r: "{{ network_vpc_region_r }}"

- include: ../../../modules/create/igw.yml
  vars:
    igw_tag_name_r: "{{ network_igw_tag_name_r }}"
    fetch:
      from: vpc_id.yml
      with:
        fetch_vpc_name_r: "{{ network_vpc_name_r }}"
        fetch_vpc_state_r: "available"

- include: ../../../modules/create/subnet.yml
  vars:
    fetch:
      from: vpc_id.yml
      with:
        fetch_vpc_name_r: "{{ network_vpc_name_r }}"
        fetch_vpc_state_r: "available"
    subnet_az_r: "{{ network_subnet_az_r }}"
    subnet_cidr_r: "{{ network_subnet_cidr_r }}"
    subnet_name_r: "{{ network_subnet_name_r }}"