- name: bootstrapping aws environments
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../vars/vars.yml

  roles:
    - {
        role: network,
        network_vpc_name_r: "{{ vpc_name }}" ,
        network_vpc_cidr_r: "{{ vpc_cidr }}",
        network_vpc_region_r: "{{ vpc_region }}" ,
        network_igw_tag_name_r: "{{ igw_tag_name }}" ,
        network_subnet_az_r: "{{ az_west_a }}" ,
        network_subnet_cidr_r: "{{ subnet_public_cidr }}" ,
        network_subnet_name_r: "{{ subnet_public_name }}"
      }