---

- name: bootstrapping aws environments
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../variables/vars.yml

#  pre_tasks:
#    - include:

  roles:
    - {
        role: hello_world,
        hello_world_mode: create,
        hello_world_name: "{{ name }}"
      }